services:
  # SERVICE BACKEND
  db:
    # SERVICE DATABASE POSTGRESQL
    image: postgres:18-alpine
    container_name: talent_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=talenta_ums
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  # SERVICE BACKEND
  backend:
    build: ./backend
    container_name: talent_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # SERVICE FRONTEND
  frontend:
    build: ./frontend
    container_name: talent_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: